---
version: '2'

services:

  postgres01:
    container_name: postgres01
    image: postgres:9.6.24-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=America/Toronto
    volumes:
      - ./data/postgres01:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command: postgres

  mqseries:
    container_name: mqserver
    image: icr.io/ibm-messaging/mq
    restart: unless-stopped
    user: "0:0"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - TZ=America/Toronto
    volumes:
      - ./data/qm1:/mnt/mqm
    ports:
      - 1414:1414
      - 9443:9443
    hostname: mq
    stdin_open: true
    tty: true

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      -  "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local